### ISSUE TITLE
WMS layers are broken in version 4.2.5 and 4.2.4

### ISSUE THREAD

**Issue by guidocalvano** [ebeaufay/UltraGlobe#10]
They do work in 4.2.1.

Anything in between I don't know...

**Comment by ebeaufay** [comment]
I made texture loading independent from terrain loading, I might have screwed something up. Also WMS support is incomplete.

Can you show me how you load the WMS layer and the service you connect to?

**Comment by ebeaufay** [comment]
I made some updates to stabilize and included cloud layers. 
The gettingStarted: https://drive.google.com/file/d/1ECn7C98WRZRlaNhz_CG5sVFWkwG4mvTb/view?usp=drive_link
and same for typescript: https://drive.google.com/file/d/1TPZiEL6xq_qNbfiWT-BE08S5SozcPc0S/view?usp=drive_link

Latest version is 4.3.7, if you get the chance to try, tell me if you have issues, WMS works for me.
