### ISSUE TITLE
Error when running base project

### ISSUE THREAD

**Issue by Biouche** [ebeaufay/UltraGlobe#15]
Hey,

I wanted to let you know that an error related to a shader is popping when running you base git code (npm install, npm run dev):

![image](https://github.com/user-attachments/assets/3343bef7-1e85-47c3-ad27-a5ca6149cae9)

I think it is related to the activation of shadows during map creation (property shadows : true).
The shader in CSMSHader.js is calling a getShadow function that doesn't seem to exist.

Regards,
Bioush

**Comment by ebeaufay** [comment]
Thanks I'll check it out. CSM is broken for latest versions of three.js but this should package a custom version, I'll check it out

**Comment by ebeaufay** [comment]
I think this is fixed, the issue was with the CSM library and has since been fixed in the latest three.js version

**Comment by Biouche** [comment]
Thx i will try this out
