### ISSUE TITLE
Google Tile3DLayer seems to disappear when rotating the camera. 

### ISSUE THREAD

**Issue by dsanjit** [ebeaufay/UltraGlobe#16]
The photorealistic 3D tiles from Google render fine but when the camera looks at certain directions the map seems to revert to a low poly version - it looks like a blurred plane is obscuring the loaded tiles.

I am using the Ultraglobe startup project.

I also seem to be getting lots of these errors in the console:

>AbortError: signal is aborted without reason
    at AbortSignal.<anonymous> (ultraglobe.min.js:2:232647)
    at n.value (ultraglobe.min.js:2:259543)
    at ultraglobe.min.js:2:260253
    at Array.forEach (<anonymous>)
    at n.value (ultraglobe.min.js:2:260216)
    at ultraglobe.min.js:2:266361
    at n.value (ultraglobe.min.js:2:266616)
    at ultraglobe.min.js:2:265447
    at Array.forEach (<anonymous>)
    at n.value (ultraglobe.min.js:2:265333)

Any suggestions?

**Comment by ebeaufay** [comment]
I think I understand the issue with google tiles.
There's a terrain layer that's on top of the tiles in the demo. you can remove it if you display google map tiles as well as the "WMS layer.

I'll make a demo specific to google 3DTiles
