### ISSUE TITLE
Google 3D tiles not rendering correctly

### ISSUE THREAD

**Issue by dsanjit** [ebeaufay/UltraGlobe#18]
The google 3D tiles sample seems to show just the atmosphere, no globe. The starter project shows the globe and the Berlin tileset correctly but when I try to add the Google tiles (with the correct API key) it doesnt show up. But strangely if I were to zoom way out and look around I can see the Google 3D globe being rendered in a different location. Suggestions?

![image](https://github.com/user-attachments/assets/1a268980-585f-4265-adb2-013ac9f4cbd1)

**Comment by ebeaufay** [comment]
I've seen this every so often. It's either a concurrency bug because the terrain tile geometries are computed in workers or it's a bug with camera and updating world matrices correctly.

I'll look out for it and fix in the future

**Comment by ebeaufay** [comment]
It's fixed in the latest version ^6.0.10
