### ISSUE TITLE
How to set camera look at a specific area on the globe

### ISSUE THREAD

**Issue by Victorfy1214** [ebeaufay/UltraGlobe#19]
I‘m building the Earth scene with this library, but I can't set a specific continent like Asia towards to the camera by default. When I change the camera position params in function `moveAndLookAt `,the direction of the axis changes too，I can't figure out how it works,I'd appreciate it if you could help me.
![QQ截图20241031173455](https://github.com/user-attachments/assets/f72e363b-b7de-4a8e-8e73-006c74b49408)
![QQ截图20241031173504](https://github.com/user-attachments/assets/8042635c-51cf-4b88-bd88-53a904e61ea9)

**Comment by ebeaufay** [comment]
you can use map#moveAndLookAt as you do

map.moveAndLookAt({ x: 138.2529, y: 36.2, z: 900000 }, { x: 138.2529, y: 36.3, z: 0}).

takes the camera desired position and target both in lon lat height

Use a slightly higher latitude for the target if you want the globe to be "straight"

**Comment by Victorfy1214** [comment]
Thank you for your patience, it works well now.
