### ISSUE TITLE
I3SLayer support "Point" layerType now,  can it support other layer type? 

### ISSUE THREAD

**Issue by wuzhenzhen1314** [ebeaufay/UltraGlobe#2]
hello，first, it is a great projection! 
I3SLayer support "Point" layerType now,  can it support other layer type? such as "IntegratedMesh"、“3DObject”...
It's hard for me to research how to render other i3s layer type use threejs.
Look forward to your reply

**Comment by ebeaufay** [comment]
Hi,
Thanks for the support.

The way I implemented it can be easily extended to the different data types. But of course each datatype brings it's own challenges.

I've been mostly working on OGC3DTiles for now but plan to get to I3S IntegratedMesh eventually. 
I can re-use a lot of the logic from 3DTiles here so it's definitely doable. 

If you have a dataset you can share, it may motivate me to prioritize :)

Do you want to do anything else other than display data?  styling, selection, labels, line of sight...

**Comment by wuzhenzhen1314** [comment]
Thank you very much for your reply！

‘https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services’，this website has rich data services，such as  I3S IntegratedMesh type、3DObject type，can be used to test。

This is my first contact with  I3S data，It is a great challenge for me to study IntegratedMesh  data format。

Now display data is the first step, there must be new demands in the future，then we will continue to communicate。

I look forward to your early support for other i3s layer type.

My English is not good, please forgive me

Still looking forward to your reply！
