### ISSUE TITLE
Can't rotate map

### ISSUE THREAD

**Issue by zeman-88** [ebeaufay/UltraGlobe#3]
Hi, thank you for this amazing project first off.

I'm trying the various examples and both on my Macbook and iPhone I can't rotate the camera, only move it around.

Is that expected? 

Thank you again.

**Comment by ebeaufay** [comment]
Just saw that too, I added the Ctrl+mouse rotation for Mac just now V2.0.8. 
For Iphone I'm not sure but I will definitely update the controls for rotation. The expected effect right now is that you rotate through double touch and moving both fingers right or left but it would probably be more intuitive to rotate the fingers around a center point

**Comment by zeman-88** [comment]
Amazing, thank you!
