### ISSUE TITLE
Scrolling and panning is too fast in custom app

### ISSUE THREAD

**Issue by snowzurfer** [ebeaufay/UltraGlobe#4]
Hi and thanks again for making this library available!

I've been working towards integrating the Google Tiles version in a Typescript + NextJS app, and I've managed to make it work and have it appear on screen the same way as in your example.

However, the scrolling and zooming is way faster than in the examples: it feels as if the controls system doesn't take into account the geometry of the globe and hence they always are at "full speed" as if you are far away from the globe.

Here's a video showing the issue I'm seeing: https://youtu.be/_GUWisGyc6Q

As you can see, when you're far from the globe, the movement is as fast as you'd expect. But zooming is way too fast, and when you manage to zoom in, then panning seems to pan more than you'd expect.

My project can be found [here](https://github.com/snowzurfer/globale), specifically I am setting up UltraGlobe [here](https://github.com/snowzurfer/globale/blob/3366c1933d84b23ac934286728b25a77cd573848/components/UltraMeshGlobe.tsx#L23) and [here](https://github.com/snowzurfer/globale/blob/3366c1933d84b23ac934286728b25a77cd573848/app/page.tsx#L14).

I'll continue investigating, but maybe you know the answer immediately?

Thank you!

**Comment by ebeaufay** [comment]
Very nice. I guess the scroll events must be interpreted differently in your environment. I will rework the controls code base on my side but in the meantime, the relevant code is in sec/controls/ZoomController line 69.

The mouse wheel event "deltaY" is probably bigger in your case for whatever reason.

**Comment by snowzurfer** [comment]
>  in the meantime, the relevant code is in sec/controls/ZoomController line 69.
cool I'll take a look.

And about the controls, it would be insanely cool if we could make them be like `MapControls`, i.e. a sort of "drop-in" like in ThreeJS rather than be baked in the system, in the long run! In the meantime other options are just as great.

**Comment by ebeaufay** [comment]
Yes I'll work towards that. At least open up the API so that custom controls can be added but mapControl/orbitControl won't work here

**Comment by snowzurfer** [comment]
Thank you, I was able to make it work as an MVP by reducing the scrolling and panning speed. Closing this

**Comment by ebeaufay** [comment]
Just one last update. the API for controllers is a bit more open now.
One can implement custom controls and add them like this

````js
import { Map, PanController, RotateController, ZoomController } from '@jdultra/ultra-globe/dist/ultraglobe.min.js';

let map = new Map({ divID: 'screen' });

map.controller.clear(); // clear existing controller chain

map.controller.append(new PanController(map.camera, map.domContainer, map));
map.controller.append(new RotateController(map.camera, map.domContainer, map));
map.controller.append(new ZoomController(map.camera, map.domContainer, map));
```` 
Chaining controllers seems the most flexible because one can potentially add extra controls like selection and decide at each step if the events are passed down the chain or not. 

Another thing to add would be to allow specifying the event that each controller responds to.
