### ISSUE TITLE
Limit navigation and Loading to a specific area

### ISSUE THREAD

**Issue by inodw1** [ebeaufay/UltraGlobe#5]
I was working on your `UltraGlobe` project and was really interested in this. Also, I was working on it to load a specific area base on the latitude and longitude.

I did it like this using GoogleMap3DTileLayer.
map.moveAndLookAt(
    { x: 140.0987606112061, y: 35.625445678544715, z: 300 },
    { x: 140.0987606112061, y: 35.625445678544715, z: 170 }
);

That conversion part works perfectly. 

But, It is caused to move my camera to that position instead of loading it to the 0, 0, 0.
I **_need to load a specific area only_**, I was **_trying to load a particular place_** on 0, 0, 0 as you did for Berlin.

I need to prevent loading more tiles when moving around the world and focus only on my initial loaded area.

**Comment by ebeaufay** [comment]
Ok I see, I could add the functionality to only load data in a specific area. With Google tiles, you'll still see data around the world but the detail would only refine in the specified area.

Another option, perhaps easier, would be to limit navigation within some bounds. Could that also suit your needs if you specify lon/lat/height bounds and the camera never leaves it?

**Comment by federicofernandez** [comment]
Related to this issue, I'm trying to remove some parts of the geometry. I was able to access the `mesh` object in the `meshCallback`. 

But when trying to filter parts of the mesh, I'm seeing coordinates that doesn't look right, both in their original system and when I convert them with `this.planet.llhToCartesian.inverse`. I'm doing this by inspecting the `geometry.position.array`, interpreting the coordinates as `[x0, y0, z0, x1, y1, z1, ... , xn, yn, zn]'.

Am I missing something? Are there other transformations being done to the geometry?

Is there any other way to at least filter out complete tiles?

Two examples:

{x: 3847.9267578125, y: 5617.9736328125, z: -7849.7705078125} (original CS)
{x: 55.06068942858773, y: -82.24084759104086, z: -6348439.601095561} (geodetic CS)
{x: 3924.8857421875, y: 5617.9736328125, z: -7849.7705078125} (original CS)
{x: 50.964483736752115, y: -81.60672774903095, z: -6348905.753842808} (geodetic CS)

Thanks in advance!

**Comment by ebeaufay** [comment]
Hi @federicofernandez 
I didn't look at the actual geometry of the google tiles to be honest but I guess there's potentially a few levels of transforms up the Object3D tree. I guess you have to apply the matrix World of the object, possibly AFTER recalculating it since the mesh might not have been rendered yet so the autoUpdate from threeJS may not have re-calculated all the matrices.

**Comment by ebeaufay** [comment]
@inodw1 I will not implement what you need in this library, I think you can achieve this more easily via the "threedtiles" librarary directly: https://github.com/ebeaufay/threedtiles/issues/16

**Comment by federicofernandez** [comment]
> Hi @federicofernandez I didn't look at the actual geometry of the google tiles to be honest but I guess there's potentially a few levels of transforms up the Object3D tree. I guess you have to apply the matrix World of the object, possibly AFTER recalculating it since the mesh might not have been rendered yet so the autoUpdate from threeJS may not have re-calculated all the matrices.

Thanks a lot for your suggestion. I'll try that.
