### ISSUE TITLE
PanController constrain axis

### ISSUE THREAD

**Issue by elmat0** [ebeaufay/UltraGlobe#6]
This is a very impressive library Emeric. Thank you for this.

I appreciate that the maths involved here is non trivial and am still struggling to grok `PanController._update()`.

When looking down on terrain in a 'plan' view, panning left right in large circular motions adds camera rotation. Is there a way to prevent this?

**Comment by ebeaufay** [comment]
Am I right to understand you'd like a kind of 2D mode where the camera is always looking straight down?

or do you mean that when the camera up vector is pointing exactly north, panning a large amount changes that.

I think it comes from the camera pitch being limited to -89° -> 89° (looking straight down messes with the other controllers (zoom especially from memory)
Also, the earth is a sphere so it's a bit tricky to keep a constant bearing for the camera up vector when panning. 
It's not impossible that I'll re-visit those controls and I'll keep this in mind but it'll be a while.

**Comment by elmat0** [comment]
Yeah the panning changes the up vector. 

I would expect when you hold and drag the cursor around, when the cursor returns to the same spot on the screen, the underlying scene should match how it started. Instead the cursor kind of drifts, like there is a compounding error and the globe itself rolls slightly in that rotation direction. You're likely right with the pitch limit being involved in this. Ah well.

It doesn't have to be perfectly 'down' or 2D, though is it possible to perhaps just gently lerp the camera back to 'plan' view on mouseup or via keypress?
